const LANGUAGE_TYPE = {
  ENGLISH: "english",
  MARATHI: "marathi",
  GUJARATI: "gujarati",
  TAMIL: "tamil",
  HINDI: "hindi",
};
const LANGUAGE = {
  english: {
    title: "Algae Store",
    Algae: "Algae",
    Store: "Store",
    selectLanguage: "Select Language",
    en: "English",
    tamil: "தமிழ்",
    gujarati: "ગુજરાતી",
    hindi: "हिंदी",
    aboutAlgaeStore: "About Algae Store",
    introducing: "Introducing",
    premiumHub: "Your Premier B2B Hub for Seaweed Trading",
    aboutAlgaeStorePara:
      "Are you in the business of seaweed cultivation, processing, or distribution? Look no further. Algae Store is your one-stop digital destination, revolutionizing the way seaweed buyers and sellers connect, collaborate, and thrive.",
    poweredBy: "Powered By",
    stats: "Stats",
    sellers: "Sellers",
    sellersPara:
      "For sellers, algae present a burgeoning market with a wide array of products. From nutritional supplements and cosmetics to biofuels and pharmaceuticals, the demand for algae-derived goods continues to grow. Capitalizing on this burgeoning demand can be a lucrative venture for entrepreneurs and distributors alike.",
    exploreAllSellers: "Explore All Sellers",
    buyers: "Buyers",
    buyersPara:
      "Seaweed buyers, explore the ocean's bounty! Seaweed offers a world of culinary delights, health benefits, and sustainable alternatives. Dive into a diverse selection of seaweed products for an eco-friendly and delicious addition to your kitchen. Embrace the sea's natural goodness today!",
    exploreAllBuyers: "Explore All Buyers",
    products: "Products",
    productsPara:
      "Discover the wonders of seaweed products. From savory snacks to skincare essentials, seaweed's versatility knows no bounds. Packed with nutrients, it promotes health and sustainability. Dive into a world of flavor, wellness, and eco-conscious choices with seaweed-based goods. Unlock the potential of the ocean's treasure!",
    exploreAllProducts: "Explore All Products",
    about: "About",
    contactUs: "Contact Us",
    aboutUs: "About Us",
    aboutUsPara:
      "Are you in the business of seaweed cultivation, processing, or distribution? Look no further. Algae Store is your one-stop digital destination, revolutionizing the way seaweed buyers and sellers connect, collaborate, and thrive.",
    unmatchedAccessibility: "Unmatched Accessibility",
    unmatchedAccessibilityPara:
      "We bring together a global network of seaweed producers, suppliers, and buyers on a single, user-friendly platform. Access new markets, forge lasting partnerships, and explore diverse seaweed products like never before.",
    seamlesslyStreamlinedTransactions: "Seamlessly Streamlined Transactions",
    seamlesslyStreamlinedTransactionsPara:
      "Our platform simplifies the entire procurement process. From negotiation to payment, we provide efficient tools and secure mechanisms to ensure smooth transactions between businesses, regardless of their geographical locations.",
    customizedSearch: "Customized Search",
    customizedSearchPara:
      "Tailor your search for seaweed products to meet your exact specifications. Whether you need raw seaweed, extracts, or specialized seaweed-based products, our advanced search filters help you find what you need quickly.",
    support247: "24/7 Support",
    support247Para:
      "Our dedicated customer support team is available around the clock to assist you. Feel confident knowing that help is just a click away.",
    globalReach: "Global Reach",
    globalReachPara:
      "Whether you are a seaweed producer in Asia, a distributor in Europe, or a researcher in North America, Algae Store bridges the geographical gaps and connects you with partners worldwide.",
    futureGrowth: "Future Growth",
    futureGrowthPara:
      "As the seaweed industry continues to expand and diversify, Algae Store evolves with it, offering you opportunities to explore new products and markets.",
    joinAlgaeStorePara:
      "Join Algae Store today and become a part of the future of the seaweed industry. Empower your business, connect with trusted partners, and help shape a more sustainable and prosperous seaweed sector. Together, we're cultivating the sea's potential.",
    registerHere: "Register Here",
    forBuyers: "For Buyers",
    forBuyersPara:
      "Are you in search of premium seaweed products to elevate your business or research efforts? Welcome to the Algae Store, your gateway to a diverse and sustainable world of seaweed sourcing. Fill up this form and then login to our portal to access the products sold.",
    submitBuyingRequest: "Submit a buying request",
    countryOfOrigin: "Country",
    cityOfOrigin: "City",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    email: "Email",
    send: "Send",
    india: "INDIA",
    goa: "GOA",
    jasonChris: "Jason Chris",
    someoneEmail: "someone@gmail.com",
    forSuppliers: "For Suppliers",
    forSuppliersPara:
      "Are you a seaweed producer, supplier, or manufacturer looking to expand your reach and connect with a global network of buyers? Look no further – our Sellers Page is your gateway to a world of opportunities in the thriving seaweed industry.",
    supplierInformationForm: "Supplier Information Form",
    organisationName: "Organisation Name",
    organisationWebsite: "Organisation Website",
    yourinterest: "What are you interested in selling",
    dummyWebsite: "www.algaestore.in",
    tellWhatSelling: "Tell us more about what you are selling!",
    productTypes: "Product Types",
    sargassum: "Sargassum",
    sargassumPara:
      "Sargassum is a brown macroalgae seaweed. Many of these species are distributed throughout the world's warm and tropical oceans, where they generally inhabit shallow waters and coral reefs. Sargassum is widely known for its free-floating growth method and this seaweed is widely used by the fertilizer, bioplastic, and animal feed industries.",
    kappaphycusAlvarezii: "Kappaphycus alvarezii",
    kappaphycusAlvareziiPara:
      "Kappaphycus alvarezii is a carrageenan-producing seaweed that is commonly used as raw material for carrageenan industries. Carrageenan is mainly used as additives for food, beverage, cosmetics, pharmaceutical, paint, textile, and other industries. Cottonii seaweeds can also be applied as a source of growth hormone which is beneficial for organic fertilizers.",
    ulvaLactuca: "Ulva lactuca",
    ulvaLactucaPara:
      "Ulva, also known as Sea Lettuce is an edible green algae is a seaweed that lives by sticking to rocks, gravel and coral reefs, but sometimes it can also be found floating in the sea.",
    geledium: "Geledium",
    gelediumPara:
      "In many countries, Gelidium is the raw material that is widely used for the extraction of high quality agar. Gelidium content is higher than Glacilaria. Traditionally Gelidium is consumed as a vegetable and to make jelly jelly. Gelidium is often eaten raw, but can also be steamed or cooked and mixed with herbs before serving.",
    gracillaria: "Gracillaria",
    gracillariaPara:
      "Gracillaria is generally used as the main raw material for the production of edible gelatin. For food applications, it is mainly used as a source of dietary fiber, solidifying agent, mixture of various beverages, thickening and stabilizing agent. For non-food applications, Glacilaria is used in the cosmetic industrial; shampoo, cream, sunscreen, toothpaste, and pharmaceutical industries.",
    getInTouch: "Get in touch",
    getInTouchPara:
      "Looking for help or a new successful partnership? Feel free to drop us a message with some details of your question. We will be happy to help you. We answer within 1 business day.",
    contactForm: "Contact Form",
    yourName: "Your Name",
    yourContactEmail: "Your Contact Email",
    yourMessage: "Your Message",
    submit: "Submit",
    enterSearch: "Enter your search here",
    search: "Search",
    filters: "Filters",
    harvested: "Harvested",
    processed: "Processed",
    finishedGoods: "Finished Goods",
    wetSeaweed: "Wet Seaweed",
    drySeaweed: "Dry Seaweed",
    seedMaterial: "Seed Material",
    all: "All",
    extractSap: "Extract/Sap",
    pulverizedSeaweed: "Pulverized Seaweed",
    powderedSeaweed: "Powdered Seaweed",
    hydrocolloids: "Hydrocolloids",
    cellulosicResidue: "Cellulosic Residue",
    agriculture: "Agriculture",
    food: "Food",
    packaging: "Packaging",
    fuel: "Fuel",
    textile: "Textile",
    cart: "CART",
    removeItem: "Remove Item",
    clearCart: "Clear Cart",
    proceed: "Proceed",
    checkout: "Checkout",
    selectedItems: "Selected Items",
    purchaseMemo: "Purchase Memo",
    number: "No",
    name: "Name",
    price: "Price",
    back: "Back",
    placeOrder: "Place Order",
    orderSubmittedSuccessfully:
      "Your order is submitted successfully, our representative will contact you soon.",
    productAddedSuccessfully: "Product Added Successfully.",
    somethingWentWrong: "Something went wrong, please try again later.'",
    buyingRequestSent:
      "Your buying request is sent to our admin, will contact you soon.",
    messageSent: "Your Message is sent to the admin, we will contact you soon",
    passwordShouldMatch: "Password and confirm password should match.",
    passwordLength: "Password should be of length greater then or equal to 8",
    invalidEmailAddress: "Please provide valid email address.",
    sellingRequestSent:
      "Your selling request is sent to our admin, will contact you soon.",
    noItemInCart: "No Item in the cart",
    editProfile: "Edit Profile",
    logout: "Logout",
    publishedProduct: "Published Product",
    welcomeAlgaeStore: "Welcome to Algae Store",
    pleaseLogin: "Please login to your account",
    username: "Username",
    password: "Password",
    logIn: "Log In",
    moreThanStore: "We are more than just a store",
    loginPara: "Login to explore all the products, buy or sell your product.",
    orders: "Orders",
    wishlist: "Wishlist",
    reviews: "Reviews",
    suppliers: "Suppliers",
    total: "Total",
    changeEmail: "Change Email (optional)",
    dontHaveAccount: "Don't have an account?",
    register: "Register",
    createYour: "Create Your",
    emailOrPhone: "Email or Phone Number",
    confirmPassword: "Confirm Password",
    alreadyAccount: "Already have an account?",
    account: "account",
    createAccount: "Create Account",
    buyer: "buyer",
    seller: "seller",
    orderHistory: "Order History",
    goToStore: "Checkout our Store",
    algaeStoreForFarmers: "Algae Store For Farmers",
    algaestoreForFarmersPara:
      "The AlgaeStore website serves as a vital lifeline for algae farmers, offering a one-stop platform for all their selling needs. AlgaeStore not only facilitates transactions but also cultivates a supportive ecosystem that propels the algae farming industry forward.",
    connectWithUs: "Connect with us",
    algaeStoreForBuyers: "Algae Store For Buyers",
    buyerDetails: "Buyer Details",
    mobileNumber: "Mobile Number",
    industry: "Industry",
    additionalInfo: "Additional Info",
    takePainOut: "Take the pain out of procurement",
    algaeStoreForBuyerInfo:
      "Algae Store is a one-stop shop for discovering and procuring biobased chemicals, ingredients, materials, and finished products.",
    buyingStep2: "Algae Store shares the request with supplier network",
    buyingStep3:
      "Receive spec sheets, quotes, and direct introductions to relevant suppliers",
    noCost:
      "There is no cost to Buyers for Algae Store’s services. Suppliers pay us a fee on completed sales.",
    gainNewCustomers: "Gain new customers without the hassle",
    algaeStoreProvides:
      "Algae Store provides suppliers with buying requests and introductions to potential customers looking for biobased products.",
    submitSupplierInfo: "Submit supplier information form.",
    step1: "Step 1",
    step2: "Step 2",
    step3: "Step 3",
    scheduleAnOnboarding:
      "Schedule an onboarding call with Algae Store to complete company and product listings.",
    reciveBuyingRequests: "Receive buying requests from potential customers.",
    noUpfrontCost:
      "There is no upfront cost to suppliers for company and product listings. As part of the onboarding process, we agree on a fee for completed sales.",
  },
  gujarati: {
    title: "શેવાળ સ્ટોર",
    Algae: "શેવાળ",
    Store: "સ્ટોર",
    selectLanguage: "ભાષા પસંદ કરો",
    en: "English",
    tamil: "தமிழ்",
    gujarati: "ગુજરાતી",
    hindi: "हिंदी",
    aboutAlgaeStore: "શેવાળ સ્ટોર વિશે",
    aboutAlgaeStorePara:
      "સીવીડ ટ્રેડિંગ માટે તમારું પ્રીમિયર B2B હબ શું તમે સીવીડની ખેતી, પ્રક્રિયા અથવા વિતરણના વ્યવસાયમાં છો? આગળ ના જુઓ. Algae Store એ તમારું વન-સ્ટોપ ડિજિટલ ડેસ્ટિનેશન છે, જે સીવીડના ખરીદદારો અને વિક્રેતાઓને જોડવાની, સહયોગ કરવા અને વિકાસ કરવાની રીતમાં ક્રાંતિ લાવે છે.",
    poweredBy: "દ્વારા સંચાલિત",
    stats: "આંકડા",
    sellers: "વિક્રેતાઓ",
    sellersPara:
      "વિક્રેતાઓ માટે, શેવાળ ઉત્પાદનોની વિશાળ શ્રેણી સાથે વધતું બજાર રજૂ કરે છે. પોષક પૂરવણીઓ અને સૌંદર્ય પ્રસાધનોથી માંડીને બાયોફ્યુઅલ અને ફાર્માસ્યુટિકલ્સ સુધી, શેવાળમાંથી મેળવેલા માલસામાનની માંગ સતત વધી રહી છે. આ વધતી માંગ પર મૂડીરોકાણ કરવું એ ઉદ્યોગસાહસિકો અને વિતરકો માટે એક નફાકારક સાહસ બની શકે છે.",
    exploreAllSellers: "બધા વિક્રેતાઓનું અન્વેષણ કરો",
    buyers: "ખરીદદારો",
    buyersPara:
      "સીવીડ ખરીદદારો, સમુદ્રની બક્ષિસનું અન્વેષણ કરો! સીવીડ રાંધણ આનંદ, આરોગ્ય લાભો અને ટકાઉ વિકલ્પોની દુનિયા પ્રદાન કરે છે. તમારા રસોડામાં પર્યાવરણને અનુકૂળ અને સ્વાદિષ્ટ ઉમેરણ માટે સીવીડ ઉત્પાદનોની વિવિધ પસંદગીમાં ડાઇવ કરો. આજે સમુદ્રની કુદરતી ભલાઈને સ્વીકારો!",
    exploreAllBuyers: "બધા ખરીદદારોનું અન્વેષણ કરો",
    products: "ઉત્પાદનો",
    productsPara:
      "સીવીડ ઉત્પાદનોની અજાયબીઓ શોધો. સેવરી નાસ્તાથી લઈને સ્કિનકેરની આવશ્યક વસ્તુઓ સુધી, સીવીડની વૈવિધ્યતાને કોઈ સીમા નથી. પોષક તત્વોથી ભરપૂર, તે આરોગ્ય અને ટકાઉપણુંને પ્રોત્સાહન આપે છે. સીવીડ-આધારિત માલસામાન સાથે સ્વાદ, સુખાકારી અને પર્યાવરણ-સભાન પસંદગીઓની દુનિયામાં ડાઇવ કરો. સમુદ્રના ખજાનાની સંભવિતતાને અનલૉક કરો!",
    about: "વિશે",
    contactUs: "અમારો સંપર્ક કરો",
    aboutUs: "અમારા વિશે",
    aboutUsPara:
      "શું તમે સીવીડની ખેતી, પ્રક્રિયા અથવા વિતરણના વ્યવસાયમાં છો? આગળ ના જુઓ. Algae Store એ તમારું વન-સ્ટોપ ડિજિટલ ડેસ્ટિનેશન છે, જે સીવીડના ખરીદદારો અને વિક્રેતાઓને જોડવાની, સહયોગ કરવા અને વિકાસ કરવાની રીતમાં ક્રાંતિ લાવે છે.",
    unmatchedAccessibility: "મેળ ન ખાતી સુલભતા",
    unmatchedAccessibilityPara:
      "અમે સીવીડ ઉત્પાદકો, સપ્લાયર્સ અને ખરીદદારોના વૈશ્વિક નેટવર્કને એક જ, વપરાશકર્તા-મૈત્રીપૂર્ણ પ્લેટફોર્મ પર એકસાથે લાવીએ છીએ. નવા બજારો ઍક્સેસ કરો, કાયમી ભાગીદારી બનાવો અને વિવિધ સીવીડ ઉત્પાદનોની શોધ કરો જેમ કે અગાઉ ક્યારેય નહીં.",
    seamlesslyStreamlinedTransactions: "એકીકૃત સુવ્યવસ્થિત વ્યવહારો",
    seamlesslyStreamlinedTransactionsPara:
      "અમારું પ્લેટફોર્મ સમગ્ર પ્રાપ્તિ પ્રક્રિયાને સરળ બનાવે છે. વાટાઘાટોથી લઈને ચુકવણી સુધી, અમે વ્યવસાયો વચ્ચે તેમના ભૌગોલિક સ્થાનોને ધ્યાનમાં લીધા વિના, સરળ વ્યવહારો સુનિશ્ચિત કરવા માટે કાર્યક્ષમ સાધનો અને સુરક્ષિત મિકેનિઝમ્સ પ્રદાન કરીએ છીએ.",
    customizedSearch: "કસ્ટમાઇઝ્ડ શોધ",
    customizedSearchPara:
      "તમારા ચોક્કસ વિશિષ્ટતાઓને પૂર્ણ કરવા માટે સીવીડ ઉત્પાદનો માટે તમારી શોધને અનુરૂપ બનાવો. ભલે તમને કાચા સીવીડ, અર્ક અથવા વિશિષ્ટ સીવીડ-આધારિત ઉત્પાદનોની જરૂર હોય, અમારા અદ્યતન શોધ ફિલ્ટર્સ તમને જે જોઈએ છે તે ઝડપથી શોધવામાં મદદ કરે છે.",
    support247: "24/7 આધાર",
    support247Para:
      "અમારી સમર્પિત ગ્રાહક સપોર્ટ ટીમ તમને મદદ કરવા ચોવીસ કલાક ઉપલબ્ધ છે. મદદ માત્ર એક ક્લિક દૂર છે તે જાણીને આત્મવિશ્વાસ અનુભવો.",
    globalReach: "વૈશ્વિક પહોંચ",
    globalReachPara:
      "ભલે તમે એશિયામાં સીવીડ ઉત્પાદક હો, યુરોપમાં વિતરક હો અથવા ઉત્તર અમેરિકામાં સંશોધક હો, Algae Store ભૌગોલિક અંતરને દૂર કરે છે અને તમને વિશ્વભરના ભાગીદારો સાથે જોડે છે.",
    futureGrowth: "ભાવિ વૃદ્ધિ",
    futureGrowthPara:
      "જેમ જેમ સીવીડ ઉદ્યોગ વિસ્તરણ અને વૈવિધ્યકરણ કરવાનું ચાલુ રાખે છે, એલ્ગી સ્ટોર તેની સાથે વિકસિત થાય છે, તમને નવા ઉત્પાદનો અને બજારોની શોધ કરવાની તકો પ્રદાન કરે છે.",
    joinAlgaeStorePara:
      "આજે જ એલ્ગી સ્ટોરમાં જોડાઓ અને સીવીડ ઉદ્યોગના ભવિષ્યનો એક ભાગ બનો. તમારા વ્યવસાયને સશક્ત કરો, વિશ્વસનીય ભાગીદારો સાથે જોડાઓ અને વધુ ટકાઉ અને સમૃદ્ધ સીવીડ ક્ષેત્રને આકાર આપવામાં સહાય કરો. સાથે મળીને, અમે સમુદ્રની સંભવિતતા કેળવી રહ્યા છીએ.",
    registerHere: "અહીં નોંધણી કરો",
    forBuyers: "ખરીદદારો માટે",
    forBuyersPara:
      "શું તમે તમારા વ્યવસાય અથવા સંશોધન પ્રયાસોને વધારવા માટે પ્રીમિયમ સીવીડ ઉત્પાદનોની શોધમાં છો? સીવીડ સોર્સિંગની વૈવિધ્યસભર અને ટકાઉ દુનિયા માટે તમારું ગેટવે, Algae Store પર આપનું સ્વાગત છે. આ ફોર્મ ભરો અને પછી વેચાયેલા ઉત્પાદનોને ઍક્સેસ કરવા માટે અમારા પોર્ટલ પર લૉગિન કરો.",
    submitBuyingRequest: "ખરીદીની વિનંતી સબમિટ કરો",
    countryOfOrigin: "દેશ",
    cityOfOrigin: "શહેર",
    fullName: "પૂરું નામ",
    phoneNumber: "ફોન નંબર",
    email: "ઈમેલ",
    send: "મોકલો",
    india: "ભારત",
    goa: "GOA",
    jasonChris: "જેસન ક્રિસ",
    someoneEmail: "someone@gmail.com",
    forSuppliers: "સપ્લાયર્સ માટે",
    forSuppliersPara:
      "શું તમે સીવીડ ઉત્પાદક, સપ્લાયર અથવા ઉત્પાદક તમારી પહોંચને વિસ્તૃત કરવા અને ખરીદદારોના વૈશ્વિક નેટવર્ક સાથે જોડાવા માંગતા હોવ? આગળ જુઓ નહીં - અમારું સેલર્સ પેજ એ સમૃદ્ધ સીવીડ ઉદ્યોગમાં તકોની દુનિયા માટે તમારું પ્રવેશદ્વાર છે.",
    supplierInformationForm: "સપ્લાયર માહિતી ફોર્મ",
    organisationName: "સંસ્થાનું નામ",
    organisationWebsite: "સંસ્થાની વેબસાઇટ",
    yourinterest: "તમને શું વેચવામાં રસ છે",
    dummyWebsite: "www.algaestore.in",
    tellWhatSelling: "તમે શું વેચો છો તે વિશે અમને વધુ કહો!",
    productTypes: "ઉત્પાદન પ્રકારો",
    sargassum: "સરગસુમ",
    sargassumPara:
      "સરગાસમ એ બ્રાઉન મેક્રોઆલ્ગી સીવીડ છે. આમાંની ઘણી પ્રજાતિઓ સમગ્ર વિશ્વના ગરમ અને ઉષ્ણકટિબંધીય મહાસાગરોમાં વિતરિત કરવામાં આવે છે, જ્યાં તેઓ સામાન્ય રીતે છીછરા પાણી અને પરવાળાના ખડકોમાં રહે છે. સરગાસમ તેની ફ્રી-ફ્લોટિંગ ગ્રોથ પદ્ધતિ માટે વ્યાપકપણે જાણીતું છે અને આ સીવીડ ખાતર, બાયોપ્લાસ્ટિક અને પશુ આહાર ઉદ્યોગો દ્વારા વ્યાપકપણે ઉપયોગમાં લેવાય છે.",
    kappaphycusAlvarezii: "કેપ્પાફીકસ અલ્વેરેઝી",
    kappaphycusAlvareziiPara:
      "Kappaphycus alvarezii એક carrageenan-ઉત્પાદક સીવીડ છે જે સામાન્ય રીતે carrageenan ઉદ્યોગો માટે કાચા માલ તરીકે વપરાય છે. Carrageenan મુખ્યત્વે ખોરાક, પીણા, સૌંદર્ય પ્રસાધનો, ફાર્માસ્યુટિકલ, રંગ, કાપડ અને અન્ય ઉદ્યોગો માટે ઉમેરણો તરીકે વપરાય છે. કોટોની સીવીડનો ઉપયોગ વૃદ્ધિ હોર્મોનના સ્ત્રોત તરીકે પણ કરી શકાય છે જે કાર્બનિક ખાતરો માટે ફાયદાકારક છે.",
    ulvaLactuca: "ઉલ્વા લેક્ટુકા",
    ulvaLactucaPara:
      "ઉલ્વા, જેને સી લેટીસ તરીકે પણ ઓળખવામાં આવે છે તે એક ખાદ્ય લીલા શેવાળ છે જે ખડકો, કાંકરી અને પરવાળાના ખડકોને વળગી રહેવાથી જીવે છે, પરંતુ ક્યારેક તે સમુદ્રમાં તરતા પણ જોવા મળે છે.",
    geledium: "ગેલેડિયમ",
    gelediumPara:
      "ઘણા દેશોમાં, ગેલિડિયમ એ કાચો માલ છે જે ઉચ્ચ ગુણવત્તાવાળા અગરના નિષ્કર્ષણ માટે વ્યાપકપણે ઉપયોગમાં લેવાય છે. ગેલિડીયમનું પ્રમાણ ગ્લેસીલેરિયા કરતા વધારે છે. પરંપરાગત રીતે ગેલિડિયમનો ઉપયોગ શાકભાજી તરીકે અને જેલી જેલી બનાવવા માટે થાય છે. ગેલિડિયમ મોટાભાગે કાચું ખાવામાં આવે છે, પરંતુ પીરસતાં પહેલાં તેને ઉકાળીને અથવા રાંધીને અને જડીબુટ્ટીઓ સાથે મિશ્રિત પણ કરી શકાય છે.",
    gracillaria: "ગ્રેસિલેરિયા",
    gracillariaPara:
      "ખાદ્ય જિલેટીનના ઉત્પાદન માટે સામાન્ય રીતે ગ્રેસીલેરિયાનો ઉપયોગ મુખ્ય કાચા માલ તરીકે થાય છે. ફૂડ એપ્લીકેશન માટે, તેનો ઉપયોગ મુખ્યત્વે ડાયેટરી ફાઇબરના સ્ત્રોત, સોલિફાઇંગ એજન્ટ, વિવિધ પીણાઓનું મિશ્રણ, ઘટ્ટ અને સ્થિરતા એજન્ટ તરીકે થાય છે. નોન-ફૂડ એપ્લીકેશન માટે, ગ્લેસીલેરિયાનો ઉપયોગ કોસ્મેટિક ઔદ્યોગિકમાં થાય છે; શેમ્પૂ, ક્રીમ, સનસ્ક્રીન, ટૂથપેસ્ટ અને ફાર્માસ્યુટિકલ ઉદ્યોગો.",
    getInTouch: "સંપર્કમાં રહેવા",
    getInTouchPara:
      "મદદ અથવા નવી સફળ ભાગીદારી જોઈએ છે? તમારા પ્રશ્નની કેટલીક વિગતો સાથે અમને સંદેશ મોકલવા માટે નિઃસંકોચ. તમને મદદ કરવામાં અમને આનંદ થશે. અમે 1 કામકાજી દિવસની અંદર જવાબ આપીએ છીએ.",
    contactForm: "સંપર્ક ફોર્મ",
    yourName: "તમારું નામ",
    yourContactEmail: "તમારો સંપર્ક ઈમેલ",
    yourMessage: "તમારો સંદેશો",
    submit: "સબમિટ કરો",
    enterSearch: "તમારી શોધ અહીં દાખલ કરો",
    search: "શોધો",
    filters: "ફિલ્ટર્સ",
    harvested: "પાક",
    processed: "પ્રક્રિયા કરેલ",
    finishedGoods: "તૈયાર માલ",
    wetSeaweed: "ભીનું સીવીડ",
    drySeaweed: "સુકા સીવીડ",
    seedMaterial: "બીજ સામગ્રી",
    all: "બધા",
    extractSap: "અર્ક/સત્વ",
    pulverizedSeaweed: "પલ્વરાઇઝ્ડ સીવીડ",
    powderedSeaweed: "પાઉડર સીવીડ",
    hydrocolloids: "હાઇડ્રોકોલોઇડ્સ",
    cellulosicResidue: "સેલ્યુલોસિક અવશેષ",
    agriculture: "કૃષિ",
    food: "ખોરાક",
    packaging: "પેકેજીંગ",
    fuel: "બળતણ",
    textile: "કાપડ",
    cart: "કાર્ટ",
    removeItem: "આઇટમ દૂર કરો",
    clearCart: "કાર્ટ સાફ કરો",
    proceed: "આગળ વધો",
    checkout: "ચેકઆઉટ",
    selectedItems: "પસંદ કરેલી વસ્તુઓ",
    purchaseMemo: "મેમો ખરીદો",
    number: "સંખ્યા",
    name: "નામ",
    price: "કિંમત",
    back: "પાછળ",
    placeOrder: "ઓર્ડર કરો",
    orderSubmittedSuccessfully:
      "તમારો ઓર્ડર સફળતાપૂર્વક સબમિટ કરવામાં આવ્યો છે, અમારા પ્રતિનિધિ ટૂંક સમયમાં તમારો સંપર્ક કરશે.",
    productAddedSuccessfully: "ઉત્પાદન સફળતાપૂર્વક ઉમેર્યું.",
    somethingWentWrong: "કંઈક ખોટું થયું. પછીથી ફરી પ્રયત્ન કરો.",
    buyingRequestSent:
      "તમારી ખરીદીની વિનંતી અમારા એડમિનને મોકલવામાં આવી છે, ટૂંક સમયમાં તમારો સંપર્ક કરશે.",
    messageSent:
      "તમારો સંદેશ એડમિનને મોકલવામાં આવ્યો છે, અમે ટૂંક સમયમાં તમારો સંપર્ક કરીશું",
    passwordShouldMatch: "પાસવર્ડ અને કન્ફર્મ પાસવર્ડ મેચ થવો જોઈએ.",
    passwordLength: "પાસવર્ડ 8 થી વધુ અથવા તેની બરાબર લંબાઈનો હોવો જોઈએ",
    invalidEmailAddress: "કૃપા કરીને માન્ય ઇમેઇલ સરનામું પ્રદાન કરો.",
    sellingRequestSent:
      "તમારી વેચાણ વિનંતી અમારા એડમિનને મોકલવામાં આવી છે, ટૂંક સમયમાં તમારો સંપર્ક કરશે.",
    noItemInCart: "કાર્ટમાં કોઈ વસ્તુ નથી",
    editProfile: "પ્રોફાઇલ સંપાદિત કરો",
    logout: "લૉગ આઉટ",
    publishedProduct: "પ્રકાશિત ઉત્પાદન",
    welcomeAlgaeStore: "શેવાળ સ્ટોર પર આપનું સ્વાગત છે",
    pleaseLogin: "કૃપા કરીને તમારા એકાઉન્ટમાં લૉગિન કરો",
    username: "વપરાશકર્તા નામ",
    password: "પાસવર્ડ",
    logIn: "પ્રવેશ કરો",
    moreThanStore: "અમે માત્ર એક સ્ટોર કરતાં વધુ છીએ",
    loginPara:
      "તમામ ઉત્પાદનોનું અન્વેષણ કરવા, તમારી પ્રોડક્ટ ખરીદવા અથવા વેચવા માટે લૉગિન કરો.",
    orders: "ઓર્ડર",
    wishlist: "વિશલિસ્ટ",
    reviews: "સમીક્ષાઓ",
    suppliers: "સપ્લાયર્સ",
    exploreAllProducts: "તમામ ઉત્પાદનોનું અન્વેષણ કરો",
    introducing: "પરિચય",
    premiumHub: "સીવીડ ટ્રેડિંગ માટે તમારું પ્રીમિયર B2B હબ",
    total: "કુલ",
    changeEmail: "ઈમેલ બદલો (વૈકલ્પિક)",
    dontHaveAccount: "ખાતું નથી?",
    register: "નોંધણી કરો",
    createYour: "તમારું બનાવો",
    emailOrPhone: "ઈમેલ અથવા ફોન નંબર",
    confirmPassword: "પાસવર્ડની પુષ્ટિ કરો",
    alreadyAccount: "પહેલેથી એકાઉન્ટ છે?",
    account: "એકાઉન્ટ",
    createAccount: "ખાતું બનાવો",
    buyer: "ખરીદનાર",
    seller: "વેચનાર",
    orderHistory: "ઓર્ડર ઇતિહાસ",
    goToStore: "અમારા સ્ટોર તપાસો",
    algaeStoreForFarmers: "ખેડૂતો માટે શેવાળ સ્ટોર",
    connectWithUs: "અમારી સાથે જોડાઓ",
    algaeStoreForBuyers: "ખરીદદારો માટે શેવાળ સ્ટોર",
    buyerDetails: "ખરીદનાર વિગતો",
    mobileNumber: "મોબાઇલ નંબર",
    industry: "ઉદ્યોગ",
    additionalInfo: "વધારાની માહીતી",
    takePainOut: "પ્રાપ્તિમાંથી પીડાને દૂર કરો",
    algaeStoreForBuyerInfo:
      "શેવાળ સ્ટોર એ જૈવ-આધારિત રસાયણો, ઘટકો, સામગ્રી અને તૈયાર ઉત્પાદનોની શોધ અને પ્રાપ્તિ માટેની વન-સ્ટોપ શોપ છે.",
    buyingStep1: "ખરીદીની વિનંતી સબમિટ કરો",
    buyingStep2: "શેવાળ સ્ટોર સપ્લાયર નેટવર્ક સાથે વિનંતી શેર કરે છે",
    buyingStep3: "સ્પેક શીટ્સ, અવતરણો અને સંબંધિત સપ્લાયર્સનો સીધો પરિચય મેળવો",
    noCost:
      "એલ્ગી સ્ટોરની સેવાઓ માટે ખરીદદારોને કોઈ ખર્ચ નથી. સપ્લાયર્સ પૂર્ણ વેચાણ પર અમને ફી ચૂકવે છે.",
    gainNewCustomers: "મુશ્કેલી વિના નવા ગ્રાહકો મેળવો",
    algaeStoreProvides:
      "એલ્ગી સ્ટોર સપ્લાયર્સને બાયોબેઝ્ડ પ્રોડક્ટ્સ શોધી રહેલા સંભવિત ગ્રાહકોને ખરીદવાની વિનંતીઓ અને પરિચય પ્રદાન કરે છે.",
    submitSupplierInfo: "સપ્લાયર માહિતી ફોર્મ સબમિટ કરો.",
    step1: "પગલું 1",
    step2: "પગલું 2",
    step3: "પગલું 3",
    scheduleAnOnboarding:
      "કંપની અને પ્રોડક્ટ લિસ્ટિંગ પૂર્ણ કરવા માટે Algae Store સાથે ઑનબોર્ડિંગ કૉલ શેડ્યૂલ કરો.",
    reciveBuyingRequests: "સંભવિત ગ્રાહકો પાસેથી ખરીદી વિનંતીઓ પ્રાપ્ત કરો.",
    noUpfrontCost:
      "કંપની અને પ્રોડક્ટ લિસ્ટિંગ માટે સપ્લાયરો માટે કોઈ અપફ્રન્ટ ખર્ચ નથી. ઓનબોર્ડિંગ પ્રક્રિયાના ભાગ રૂપે, અમે પૂર્ણ વેચાણ માટે ફી પર સંમત છીએ.",
  },
  hindi: {
    title: "शैवाल भण्डार",
    Algae: "शैवाल",
    Store: "भण्डार",
    selectLanguage: "भाषा चुने",
    en: "English",
    tamil: "தமிழ்",
    gujarati: "ગુજરાતી",
    hindi: "हिंदी",
    aboutAlgaeStore: "शैवाल भंडार के बारे में",
    aboutAlgaeStorePara:
      "समुद्री शैवाल व्यापार के लिए आपका प्रीमियर बी2बी हब क्या आप समुद्री शैवाल की खेती, प्रसंस्करण या वितरण के व्यवसाय में हैं? आगे कोई तलाश नहीं करें। शैवाल स्टोर आपका वन-स्टॉप डिजिटल गंतव्य है, जो समुद्री शैवाल खरीदारों और विक्रेताओं के जुड़ने, सहयोग करने और फलने-फूलने के तरीके में क्रांतिकारी बदलाव ला रहा है।",
    poweredBy: "द्वारा संचालित",
    stats: "आँकड़े",
    sellers: "सेलर्स",
    sellersPara:
      "विक्रेताओं के लिए, शैवाल उत्पादों की एक विस्तृत श्रृंखला के साथ एक बढ़ता हुआ बाज़ार प्रस्तुत करता है। पोषक तत्वों की खुराक और सौंदर्य प्रसाधनों से लेकर जैव ईंधन और फार्मास्यूटिकल्स तक, शैवाल-व्युत्पन्न वस्तुओं की मांग लगातार बढ़ रही है। इस बढ़ती मांग का लाभ उठाना उद्यमियों और वितरकों दोनों के लिए एक आकर्षक उद्यम हो सकता है।",
    exploreAllSellers: "सभी विक्रेताओं का अन्वेषण करें",
    buyers: "खरीदार",
    buyersPara:
      "समुद्री शैवाल ख़रीदारों, सागर की प्रचुरता का अन्वेषण करें! समुद्री शैवाल पाक आनंद, स्वास्थ्य लाभ और टिकाऊ विकल्पों की एक दुनिया प्रदान करता है। अपनी रसोई में पर्यावरण-अनुकूल और स्वादिष्ट व्यंजन जोड़ने के लिए समुद्री शैवाल उत्पादों के विविध चयन में गोता लगाएँ। आज ही समुद्र की प्राकृतिक अच्छाई को अपनाएं!",
    exploreAllBuyers: "सभी खरीदारों का अन्वेषण करें",
    products: "उत्पादों",
    productsPara:
      "समुद्री शैवाल उत्पादों के चमत्कारों की खोज करें। स्वादिष्ट नाश्ते से लेकर त्वचा की देखभाल की आवश्यक वस्तुओं तक, समुद्री शैवाल की बहुमुखी प्रतिभा की कोई सीमा नहीं है। पोषक तत्वों से भरपूर, यह स्वास्थ्य और स्थिरता को बढ़ावा देता है। समुद्री शैवाल-आधारित वस्तुओं के साथ स्वाद, स्वास्थ्य और पर्यावरण के प्रति जागरूक विकल्पों की दुनिया में उतरें। सागर के खजाने की क्षमता को अनलॉक करें!",
    about: "बारे में",
    contactUs: "संपर्क करें",
    aboutUs: "हमारे बारे में",
    aboutUsPara:
      "क्या आप समुद्री शैवाल की खेती, प्रसंस्करण या वितरण के व्यवसाय में हैं? आगे कोई तलाश नहीं करें। शैवाल स्टोर आपका वन-स्टॉप डिजिटल गंतव्य है, जो समुद्री शैवाल खरीदारों और विक्रेताओं के जुड़ने, सहयोग करने और फलने-फूलने के तरीके में क्रांतिकारी बदलाव ला रहा है।",
    unmatchedAccessibility: "बेजोड़ पहुंच",
    unmatchedAccessibilityPara:
      "हम समुद्री शैवाल उत्पादकों, आपूर्तिकर्ताओं और खरीदारों के एक वैश्विक नेटवर्क को एक उपयोगकर्ता-अनुकूल मंच पर एक साथ लाते हैं। नए बाज़ारों तक पहुंचें, स्थायी साझेदारियां बनाएं और विविध समुद्री शैवाल उत्पादों का पता लगाएं, जैसा पहले कभी नहीं हुआ।",
    seamlesslyStreamlinedTransactions: "निर्बाध रूप से सुव्यवस्थित लेनदेन",
    seamlesslyStreamlinedTransactionsPara:
      "हमारा प्लेटफ़ॉर्म संपूर्ण खरीद प्रक्रिया को सरल बनाता है। बातचीत से लेकर भुगतान तक, हम व्यवसायों के बीच उनके भौगोलिक स्थानों की परवाह किए बिना सुचारू लेनदेन सुनिश्चित करने के लिए कुशल उपकरण और सुरक्षित तंत्र प्रदान करते हैं।",
    customizedSearch: "अनुकूलित खोज",
    customizedSearchPara:
      "समुद्री शैवाल उत्पादों के लिए अपनी खोज को अपने सटीक विनिर्देशों के अनुरूप बनाएं। चाहे आपको कच्चे समुद्री शैवाल, अर्क, या विशेष समुद्री शैवाल-आधारित उत्पादों की आवश्यकता हो, हमारे उन्नत खोज फ़िल्टर आपको वह ढूंढने में मदद करते हैं जिसकी आपको तुरंत आवश्यकता है।",
    support247: "24/7 सहायता",
    support247Para:
      "हमारी समर्पित ग्राहक सहायता टीम आपकी सहायता के लिए चौबीसों घंटे उपलब्ध है। यह जानकर आश्वस्त महसूस करें कि सहायता बस एक क्लिक दूर है।",
    globalReach: "विश्वव्यापी पहुँच",
    globalReachPara:
      "चाहे आप एशिया में समुद्री शैवाल उत्पादक हों, यूरोप में वितरक हों, या उत्तरी अमेरिका में शोधकर्ता हों, शैवाल स्टोर भौगोलिक अंतराल को पाटता है और आपको दुनिया भर के भागीदारों से जोड़ता है।",
    futureGrowth: "भविष्य का विकास",
    futureGrowthPara:
      "जैसे-जैसे समुद्री शैवाल उद्योग का विस्तार और विविधता जारी है, शैवाल स्टोर इसके साथ विकसित होता है, जो आपको नए उत्पादों और बाजारों का पता लगाने के अवसर प्रदान करता है।",
    joinAlgaeStorePara:
      "आज ही शैवाल स्टोर से जुड़ें और समुद्री शैवाल उद्योग के भविष्य का हिस्सा बनें। अपने व्यवसाय को सशक्त बनाएं, विश्वसनीय साझेदारों से जुड़ें और अधिक टिकाऊ और समृद्ध समुद्री शैवाल क्षेत्र को आकार देने में मदद करें। हम साथ मिलकर समुद्र की क्षमता का विकास कर रहे हैं।",
    registerHere: "यहां रजिस्टर करें",
    forBuyers: "खरीददारों के लिए",
    forBuyersPara:
      "क्या आप अपने व्यवसाय या अनुसंधान प्रयासों को बढ़ाने के लिए प्रीमियम समुद्री शैवाल उत्पादों की तलाश में हैं? शैवाल स्टोर में आपका स्वागत है, जो समुद्री शैवाल सोर्सिंग की विविध और टिकाऊ दुनिया के लिए आपका प्रवेश द्वार है। इस फॉर्म को भरें और फिर बेचे गए उत्पादों तक पहुंचने के लिए हमारे पोर्टल पर लॉग इन करें।",
    submitBuyingRequest: "खरीदारी अनुरोध सबमिट करें",
    countryOfOrigin: "देश",
    cityOfOrigin: "शहर",
    fullName: "पूरा नाम",
    phoneNumber: "फ़ोन नंबर",
    email: "ईमेल",
    send: "भेजना",
    india: "भारत",
    goa: "गोवा",
    jasonChris: "जेसन क्रिस",
    someoneEmail: "someone@gmail.com",
    forSuppliers: "आपूर्तिकर्ताओं के लिए",
    forSuppliersPara:
      "क्या आप एक समुद्री शैवाल उत्पादक, आपूर्तिकर्ता या विनिर्माता हैं जो अपनी पहुंच का विस्तार करना चाहते हैं और खरीदारों के वैश्विक नेटवर्क से जुड़ना चाहते हैं? आगे मत देखो - हमारा विक्रेता पृष्ठ संपन्न समुद्री शैवाल उद्योग में अवसरों की दुनिया के लिए आपका प्रवेश द्वार है।",
    supplierInformationForm: "आपूर्तिकर्ता सूचना प्रपत्र",
    organisationName: "संगठन का नाम",
    organisationWebsite: "संगठन की वेबसाइट",
    yourinterest: "आपको क्या बेचने में रुचि है",
    dummyWebsite: "www.algaestore.in",
    tellWhatSelling: "आप क्या बेच रहे हैं इसके बारे में हमें और बताएं!",
    productTypes: "उत्पाद प्रकार",
    sargassum: "सरगसुम",
    sargassumPara:
      "सरगासुम एक भूरे मैक्रोएल्गे समुद्री शैवाल है। इनमें से कई प्रजातियाँ दुनिया के गर्म और उष्णकटिबंधीय महासागरों में वितरित की जाती हैं, जहाँ वे आम तौर पर उथले पानी और प्रवाल भित्तियों में निवास करती हैं। सरगासुम व्यापक रूप से अपनी मुक्त-फ्लोटिंग विकास पद्धति के लिए जाना जाता है और इस समुद्री शैवाल का व्यापक रूप से उर्वरक, बायोप्लास्टिक और पशु चारा उद्योगों द्वारा उपयोग किया जाता है।",
    kappaphycusAlvarezii: "कप्पाफाइकस अल्वारेज़ी",
    kappaphycusAlvareziiPara:
      "कप्पाफाइकस अल्वारेज़ी एक कैरेजेनन-उत्पादक समुद्री शैवाल है जिसे आमतौर पर कैरेजेनन उद्योगों के लिए कच्चे माल के रूप में उपयोग किया जाता है। कैरेजेनन का उपयोग मुख्य रूप से भोजन, पेय पदार्थ, सौंदर्य प्रसाधन, दवा, पेंट, कपड़ा और अन्य उद्योगों के लिए योजक के रूप में किया जाता है। कॉटनी समुद्री शैवाल को विकास हार्मोन के स्रोत के रूप में भी लगाया जा सकता है जो जैविक उर्वरकों के लिए फायदेमंद है।",
    ulvaLactuca: "उलवा लैक्टुका",
    ulvaLactucaPara:
      "उल्वा, जिसे सी लेट्यूस के नाम से भी जाना जाता है, एक खाद्य हरा शैवाल है, एक समुद्री शैवाल है जो चट्टानों, बजरी और मूंगा चट्टानों से चिपककर रहता है, लेकिन कभी-कभी यह समुद्र में तैरता हुआ भी पाया जा सकता है।",
    geledium: "जेलेडियम",
    gelediumPara:
      "कई देशों में, गेलिडियम वह कच्चा माल है जिसका उपयोग उच्च गुणवत्ता वाले अगर के निष्कर्षण के लिए व्यापक रूप से किया जाता है। ग्लेसीलेरिया की तुलना में जेलिडियम की मात्रा अधिक होती है। परंपरागत रूप से जेलिडियम का सेवन सब्जी के रूप में और जेली जेली बनाने के लिए किया जाता है। गेलिडियम को अक्सर कच्चा खाया जाता है, लेकिन इसे भाप में भी पकाया जा सकता है या पकाया जा सकता है और परोसने से पहले जड़ी-बूटियों के साथ मिलाया जा सकता है।",
    gracillaria: "gracilaria",
    gracillariaPara:
      "ग्रेसिलेरिया का उपयोग आम तौर पर खाद्य जिलेटिन के उत्पादन के लिए मुख्य कच्चे माल के रूप में किया जाता है। खाद्य अनुप्रयोगों के लिए, इसका उपयोग मुख्य रूप से आहार फाइबर, ठोस बनाने वाले एजेंट, विभिन्न पेय पदार्थों के मिश्रण, गाढ़ा करने और स्थिर करने वाले एजेंट के रूप में किया जाता है। गैर-खाद्य अनुप्रयोगों के लिए, ग्लेसीलेरिया का उपयोग कॉस्मेटिक औद्योगिक में किया जाता है; शैम्पू, क्रीम, सनस्क्रीन, टूथपेस्ट और दवा उद्योग।",
    getInTouch: "संपर्क में रहो",
    getInTouchPara:
      "मदद या नई सफल साझेदारी की तलाश है? बेझिझक हमें अपने प्रश्न के कुछ विवरण के साथ एक संदेश भेजें। हमें आपकी मदद करने में ख़ुशी होगी। हम 1 कार्य दिवस के भीतर उत्तर देते हैं।",
    contactForm: "संपर्क करें प्रपत्र",
    yourName: "आपका नाम",
    yourContactEmail: "आपका संपर्क ईमेल",
    yourMessage: "आपका संदेश",
    submit: "जमा करना",
    enterSearch: "अपनी खोज यहां दर्ज करें",
    search: "खोज",
    filters: "फिल्टर",
    harvested: "काटा",
    processed: "प्रसंस्कृत",
    finishedGoods: "तैयार माल",
    wetSeaweed: "गीला समुद्री शैवाल",
    drySeaweed: "सूखी समुद्री शैवाल",
    seedMaterial: "बीज सामग्री",
    all: "सभी",
    extractSap: "अर्क/सैप",
    pulverizedSeaweed: "चूर्णित समुद्री शैवाल",
    powderedSeaweed: "पीसा हुआ समुद्री शैवाल",
    hydrocolloids: "हाइड्रोकोलॉइड्स",
    cellulosicResidue: "सेल्युलोसिक अवशेष",
    agriculture: "कृषि",
    food: "खाना",
    packaging: "पैकेजिंग",
    fuel: "ईंधन",
    textile: "कपड़ा",
    cart: "कार्ट",
    removeItem: "वस्तु निकालें",
    clearCart: "कार्ट को खाली करें",
    proceed: "आगे बढ़ना",
    checkout: "चेक आउट",
    selectedItems: "चयनित उत्पाद",
    purchaseMemo: "क्रय मेमो",
    number: "संख्या",
    name: "नाम",
    price: "कीमत",
    back: "पीछे",
    placeOrder: "आदेश देना",
    orderSubmittedSuccessfully:
      "आपका ऑर्डर सफलतापूर्वक सबमिट हो गया है, हमारा प्रतिनिधि जल्द ही आपसे संपर्क करेगा।",
    productAddedSuccessfully: "उत्पाद सफलतापूर्वक जोड़ा गया.",
    somethingWentWrong: "कुछ गलत हो गया है। कृपया बाद में दोबारा प्रयास करें।",
    buyingRequestSent:
      "आपका खरीदारी अनुरोध हमारे व्यवस्थापक को भेज दिया गया है, जल्द ही आपसे संपर्क किया जाएगा।",
    messageSent:
      "आपका संदेश एडमिन को भेज दिया गया है, हम जल्द ही आपसे संपर्क करेंगे",
    passwordShouldMatch: "पासवर्ड और कन्फर्म पासवर्ड मेल खाना चाहिए।",
    passwordLength: "पासवर्ड की लंबाई 8 से अधिक या उसके बराबर होनी चाहिए",
    invalidEmailAddress: "कृपया वैध ईमेल पता प्रदान करें",
    sellingRequestSent:
      "आपका विक्रय अनुरोध हमारे व्यवस्थापक को भेज दिया गया है, शीघ्र ही आपसे संपर्क किया जाएगा।",
    noItemInCart: "कार्ट में कोई आइटम नहीं",
    editProfile: "प्रोफ़ाइल संपादित करें",
    logout: "लॉग आउट",
    publishedProduct: "प्रकाशित उत्पाद",
    welcomeAlgaeStore: "शैवाल स्टोर में आपका स्वागत है",
    pleaseLogin: "कृपया अपने खाते लॉग इन करें",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    logIn: "लॉग इन करें",
    moreThanStore: "हम सिर्फ एक स्टोर से कहीं अधिक हैं",
    loginPara:
      "सभी उत्पादों का पता लगाने, अपना उत्पाद खरीदने या बेचने के लिए लॉगिन करें।",
    orders: "आदेश",
    wishlist: "इच्छा-सूची",
    reviews: "समीक्षा",
    suppliers: "आपूर्तिकर्ता",
    exploreAllProducts: "सभी उत्पादों का अन्वेषण करें",
    introducing: "परिचय",
    premiumHub: "समुद्री शैवाल व्यापार के लिए आपका प्रीमियर बी2बी हब",
    total: "कुल",
    changeEmail: "ईमेल बदलें (वैकल्पिक)",
    dontHaveAccount: "कोई खाता नहीं है?",
    register: "पंजीकरण करवाना",
    createYour: "अपना बनाएं",
    emailOrPhone: "ईमेल या फ़ोन नंबर",
    confirmPassword: "पासवर्ड की पुष्टि कीजिये",
    alreadyAccount: "क्या आपके पास पहले से एक खाता मौजूद है?",
    account: "खाता",
    createAccount: "खाता बनाएं",
    buyer: "क्रेता",
    seller: "विक्रेता",
    orderHistory: "आदेश इतिहास",
    goToStore: "हमारे स्टोर को चेकआउट करें",
    algaeStoreForFarmers: "किसानों के लिए शैवाल भंडार",
    connectWithUs: "हमारे साथ जुड़ें",
    algaeStoreForBuyers: "खरीददारों के लिए शैवाल भंडार",
    buyerDetails: "क्रेता विवरण",
    mobileNumber: "मोबाईल नंबर",
    industry: "उद्योग",
    additionalInfo: "अतिरिक्त जानकारी",
    takePainOut: "खरीदारी का कष्ट दूर करें",
    algaeStoreForBuyerInfo:
      "शैवाल स्टोर जैव आधारित रसायनों, अवयवों, सामग्रियों और तैयार उत्पादों की खोज और खरीद के लिए वन-स्टॉप शॉप है।",
    buyingStep1: "खरीदारी अनुरोध सबमिट करें",
    buyingStep2: "शैवाल स्टोर आपूर्तिकर्ता नेटवर्क के साथ अनुरोध साझा करता है",
    buyingStep3:
      "प्रासंगिक आपूर्तिकर्ताओं से विशिष्ट पत्रक, उद्धरण और प्रत्यक्ष परिचय प्राप्त करें",
    noCost:
      "शैवाल स्टोर की सेवाओं के लिए खरीदारों को कोई शुल्क नहीं देना पड़ता है। आपूर्तिकर्ता हमें पूरी बिक्री पर शुल्क का भुगतान करते हैं।",
    gainNewCustomers: "बिना किसी परेशानी के नए ग्राहक प्राप्त करें",
    algaeStoreProvides:
      "शैवाल स्टोर आपूर्तिकर्ताओं को जैव-आधारित उत्पादों की तलाश करने वाले संभावित ग्राहकों को खरीद अनुरोध और परिचय प्रदान करता है।",
    submitSupplierInfo: "आपूर्तिकर्ता सूचना प्रपत्र जमा करें.",
    step1: "चरण 1",
    step2: "चरण 2",
    step3: "चरण 3",
    scheduleAnOnboarding:
      "कंपनी और उत्पाद लिस्टिंग को पूरा करने के लिए शैवाल स्टोर के साथ ऑनबोर्डिंग कॉल शेड्यूल करें।",
    reciveBuyingRequests: "संभावित ग्राहकों से खरीदारी के अनुरोध प्राप्त करें।",
    noUpfrontCost:
      "कंपनी और उत्पाद लिस्टिंग के लिए आपूर्तिकर्ताओं से कोई अग्रिम लागत नहीं ली जाती है। ऑनबोर्डिंग प्रक्रिया के भाग के रूप में, हम पूर्ण बिक्री के लिए शुल्क पर सहमत हैं।",
  },
  marathi: {
    title: "एकपेशीय वनस्पती स्टोअर",
    Algae: "एकपेशीय वनस्पती",
    Store: "स्टोअर",
    selectLanguage: "भाषा निवडा",
    en: "इंग्रजी",
    marathi: "मराठी",
    tamil: "तमिळ",
    goToStore: "आमचे स्टोअर तपासा",
    algaeStoreForFarmers: "शेतकऱ्यांसाठी शैवाल स्टोअर",
    connectWithUs: "आमच्याशी कनेक्ट व्हा",
    algaeStoreForBuyers: "खरेदीदारांसाठी एकपेशीय वनस्पती स्टोअर",
    buyerDetails: "खरेदीदार तपशील",
    mobileNumber: "मोबाइल नंबर",
    sellersPara:
      "विक्रेत्यांसाठी, एकपेशीय वनस्पती उत्पादनांच्या विस्तृत श्रेणीसह वाढणारी बाजारपेठ सादर करते. पौष्टिक पूरक आणि सौंदर्यप्रसाधनांपासून ते जैवइंधन आणि फार्मास्युटिकल्सपर्यंत, शैवाल-व्युत्पन्न वस्तूंची मागणी सतत वाढत आहे. या वाढत्या मागणीचे भांडवल करणे हे उद्योजक आणि वितरकांसाठी एक फायदेशीर उपक्रम असू शकते.",
    industry: "उद्योग",
    additionalInfo: "अतिरिक्त माहिती",
    takePainOut: "प्राप्तीतून वेदना काढा",
    algaeStoreForBuyerInfo:
      "शैवाल स्टोअर हे बायोबेस्ड रसायने, घटक, साहित्य आणि तयार उत्पादने शोधण्यासाठी आणि खरेदी करण्यासाठी एक-स्टॉप शॉप आहे.",
    buyingStep1: "खरेदी विनंती सबमिट करा",
    buyingStep2: "शैवाल स्टोअर पुरवठादार नेटवर्कसह विनंती सामायिक करते",
    buyingStep3:
      "संबंधित पुरवठादारांना विशिष्ट पत्रके, कोट आणि थेट परिचय प्राप्त करा",
    noCost:
      "शैवाल स्टोअरच्या सेवांसाठी खरेदीदारांना कोणतेही शुल्क नाही. पूर्ण झालेल्या विक्रीवर पुरवठादार आम्हाला शुल्क देतात.",
    gainNewCustomers: "त्रास न होता नवीन ग्राहक मिळवा",
    algaeStoreProvides:
      "शैवाल स्टोअर पुरवठादारांना बायोबेस्ड उत्पादने शोधत असलेल्या संभाव्य ग्राहकांना खरेदी विनंत्या आणि परिचय प्रदान करते.",
    submitSupplierInfo: "पुरवठादार माहिती फॉर्म सबमिट करा.",
    step1: "पायरी 1",
    step2: "पायरी 2",
    step3: "पायरी 3",
    scheduleAnOnboarding:
      "कंपनी आणि उत्पादन सूची पूर्ण करण्यासाठी एकपेशीय वनस्पती स्टोअर सह ऑनबोर्डिंग कॉल शेड्यूल करा.",
    reciveBuyingRequests: "संभाव्य ग्राहकांकडून खरेदी विनंत्या प्राप्त करा.",
    noUpfrontCost:
      "कंपनी आणि उत्पादन सूचीसाठी पुरवठादारांना कोणतीही आगाऊ किंमत नाही. ऑनबोर्डिंग प्रक्रियेचा एक भाग म्हणून, आम्ही पूर्ण केलेल्या विक्रीसाठी शुल्कावर सहमत आहोत.",
  },
  tamil: {
    title: "பாசி கடை",
    Algae: "பாசி",
    Store: "கடை",
    selectLanguage: "மொழியை தேர்ந்தெடுங்கள்",
    en: "English",
    tamil: "தமிழ்",
    gujarati: "ગુજરાતી",
    hindi: "हिंदी",
    aboutAlgaeStore: "பாசி கடை பற்றி",
    aboutAlgaeStorePara:
      "கடற்பாசி வர்த்தகத்திற்கான உங்கள் பிரீமியர் பி2பி ஹப் நீங்கள் கடற்பாசி சாகுபடி, பதப்படுத்துதல் அல்லது விநியோகம் செய்யும் தொழிலில் இருக்கிறீர்களா? மேலும் பார்க்க வேண்டாம். கடற்பாசி வாங்குபவர்களும் விற்பவர்களும் இணையும், ஒத்துழைத்து, செழித்து வளரும் விதத்தில் புரட்சியை ஏற்படுத்தும் ஆல்கே ஸ்டோர் உங்களின் ஒரே டிஜிட்டல் இலக்காகும்.",
    poweredBy: "மூலம் இயக்கப்படுகிறது",
    stats: "புள்ளிவிவரங்கள்",
    sellers: "விற்பனையாளர்கள்",
    sellersPara:
      "விற்பனையாளர்களுக்கு, பாசிகள் பரந்த அளவிலான தயாரிப்புகளுடன் வளர்ந்து வரும் சந்தையை வழங்குகின்றன. ஊட்டச்சத்து சப்ளிமெண்ட்ஸ் மற்றும் அழகுசாதனப் பொருட்களில் இருந்து உயிரி எரிபொருள்கள் மற்றும் மருந்துகள் வரை, பாசியிலிருந்து பெறப்பட்ட பொருட்களின் தேவை தொடர்ந்து அதிகரித்து வருகிறது. இந்த வளர்ந்து வரும் தேவையை மூலதனமாக்குவது தொழில்முனைவோர் மற்றும் விநியோகஸ்தர்களுக்கு லாபகரமான முயற்சியாக இருக்கும்.",
    exploreAllSellers: "அனைத்து விற்பனையாளர்களையும் ஆராயுங்கள்",
    buyers: "வாங்குபவர்கள்",
    buyersPara:
      "கடற்பாசி வாங்குபவர்களே, கடலின் அருட்கொடையை ஆராயுங்கள்! கடற்பாசி சமையல் மகிழ்வுகள், சுகாதார நலன்கள் மற்றும் நிலையான மாற்றுகளின் உலகத்தை வழங்குகிறது. உங்கள் சமையலறையில் சுற்றுச்சூழலுக்கு உகந்த மற்றும் சுவையான கூடுதலாக கடற்பாசி தயாரிப்புகளின் பல்வேறு தேர்வுகளில் முழுக்குங்கள். கடலின் இயற்கை நற்குணத்தை இன்று தழுவுங்கள்!",
    exploreAllBuyers: "அனைத்து வாங்குபவர்களையும் ஆராயுங்கள்",
    products: "தயாரிப்புகள்",
    productsPara:
      "கடற்பாசி பொருட்களின் அதிசயங்களைக் கண்டறியவும். சுவையான தின்பண்டங்கள் முதல் தோல் பராமரிப்பு அத்தியாவசியங்கள் வரை, கடற்பாசியின் பல்துறைக்கு எல்லையே இல்லை. ஊட்டச்சத்துக்கள் நிரம்பியுள்ளது, இது ஆரோக்கியத்தையும் நிலைத்தன்மையையும் மேம்படுத்துகிறது. கடற்பாசி சார்ந்த பொருட்களுடன் சுவை, ஆரோக்கியம் மற்றும் சூழல் உணர்வுள்ள தேர்வுகள் நிறைந்த உலகில் முழுக்குங்கள். கடலின் புதையலின் திறனைத் திறக்கவும்!",
    about: "பற்றி",
    contactUs: "எங்களை தொடர்பு கொள்ள",
    aboutUs: "எங்களை பற்றி",
    aboutUsPara:
      "நீங்கள் கடற்பாசி சாகுபடி, பதப்படுத்துதல் அல்லது விநியோகம் செய்யும் தொழிலில் இருக்கிறீர்களா? மேலும் பார்க்க வேண்டாம். கடற்பாசி வாங்குபவர்களும் விற்பவர்களும் இணையும், ஒத்துழைத்து, செழித்து வளரும் விதத்தில் புரட்சியை ஏற்படுத்தும் ஆல்கே ஸ்டோர் உங்களின் ஒரே டிஜிட்டல் இலக்காகும்.",
    unmatchedAccessibility: "பொருத்தமற்ற அணுகல்தன்மை",
    unmatchedAccessibilityPara:
      "கடற்பாசி உற்பத்தியாளர்கள், சப்ளையர்கள் மற்றும் வாங்குபவர்களின் உலகளாவிய வலையமைப்பை ஒரே, பயனர் நட்பு மேடையில் நாங்கள் ஒன்றிணைக்கிறோம். புதிய சந்தைகளை அணுகவும், நீடித்த கூட்டாண்மைகளை உருவாக்கவும், முன் எப்போதும் இல்லாத வகையில் பல்வேறு கடற்பாசி தயாரிப்புகளை ஆராயவும்.",
    seamlesslyStreamlinedTransactions:
      "தடையின்றி நெறிப்படுத்தப்பட்ட பரிவர்த்தனைகள்",
    seamlesslyStreamlinedTransactionsPara:
      "எங்கள் தளம் முழு கொள்முதல் செயல்முறையையும் எளிதாக்குகிறது. பேச்சுவார்த்தையில் இருந்து பணம் செலுத்துவது வரை, வணிகங்களின் புவியியல் இருப்பிடத்தைப் பொருட்படுத்தாமல், வணிகங்களுக்கு இடையே சுமூகமான பரிவர்த்தனைகளை உறுதி செய்வதற்கான திறமையான கருவிகள் மற்றும் பாதுகாப்பான வழிமுறைகளை நாங்கள் வழங்குகிறோம்.",
    customizedSearch: "தனிப்பயனாக்கப்பட்ட தேடல்",
    customizedSearchPara:
      "உங்கள் துல்லியமான விவரக்குறிப்புகளைப் பூர்த்தி செய்ய கடற்பாசி தயாரிப்புகளைத் தேடுங்கள். உங்களுக்கு மூல கடற்பாசி, சாறுகள் அல்லது பிரத்யேக கடற்பாசி சார்ந்த தயாரிப்புகள் தேவைப்பட்டாலும், எங்களின் மேம்பட்ட தேடல் வடிப்பான்கள் உங்களுக்குத் தேவையானதை விரைவாகக் கண்டறிய உதவுகின்றன.",
    support247: "24/7 ஆதரவு",
    support247Para:
      "உங்களுக்கு உதவ எங்கள் பிரத்யேக வாடிக்கையாளர் ஆதரவுக் குழு 24 மணி நேரமும் உள்ளது. உதவி ஒரு கிளிக்கில் உள்ளது என்பதை அறிந்து நம்பிக்கையுடன் இருங்கள்.",
    globalReach: "குளோபல் ரீச்",
    globalReachPara:
      "நீங்கள் ஆசியாவில் கடற்பாசி தயாரிப்பாளராக இருந்தாலும், ஐரோப்பாவில் விநியோகஸ்தராக இருந்தாலும் அல்லது வட அமெரிக்காவில் ஆராய்ச்சியாளராக இருந்தாலும், ஆல்கே ஸ்டோர் புவியியல் இடைவெளிகளைக் குறைத்து உங்களை உலகெங்கிலும் உள்ள கூட்டாளர்களுடன் இணைக்கிறது.",
    futureGrowth: "எதிர்கால வளர்ச்சி",
    futureGrowthPara:
      "கடற்பாசி தொழில் தொடர்ந்து விரிவடைந்து பல்வகைப்படுத்தப்படுவதால், ஆல்கா ஸ்டோர் அதனுடன் உருவாகிறது, புதிய தயாரிப்புகள் மற்றும் சந்தைகளை ஆராய்வதற்கான வாய்ப்புகளை உங்களுக்கு வழங்குகிறது.",
    joinAlgaeStorePara:
      "இன்றே ஆல்கா ஸ்டோரில் சேர்ந்து, கடற்பாசி தொழிலின் எதிர்காலத்தின் ஒரு பகுதியாக மாறுங்கள். உங்கள் வணிகத்தை மேம்படுத்தவும், நம்பகமான கூட்டாளர்களுடன் இணைக்கவும், மேலும் நிலையான மற்றும் வளமான கடற்பாசி துறையை வடிவமைக்க உதவுங்கள். ஒன்றாக, நாங்கள் கடலின் திறனை வளர்க்கிறோம்.",
    registerHere: "இங்கே பதிவு செய்யவும்",
    forBuyers: "வாங்குபவர்களுக்கு",
    forBuyersPara:
      "உங்கள் வணிகம் அல்லது ஆராய்ச்சி முயற்சிகளை உயர்த்த பிரீமியம் கடற்பாசி தயாரிப்புகளைத் தேடுகிறீர்களா? ஆல்கே ஸ்டோருக்கு வரவேற்கிறோம், இது கடற்பாசி ஆதாரத்தின் மாறுபட்ட மற்றும் நிலையான உலகத்திற்கான உங்கள் நுழைவாயில். இந்த படிவத்தை பூர்த்தி செய்து, பின்னர் விற்கப்படும் தயாரிப்புகளை அணுக எங்கள் போர்ட்டலில் உள்நுழைக.",
    submitBuyingRequest: "வாங்குதல் கோரிக்கையைச் சமர்ப்பிக்கவும்",
    countryOfOrigin: "நாடு",
    cityOfOrigin: "நகரம்",
    fullName: "முழு பெயர்",
    phoneNumber: "தொலைபேசி எண்",
    email: "மின்னஞ்சல்",
    send: "அனுப்பு",
    india: "இந்தியா",
    goa: "GOA",
    jasonChris: "ஜேசன் கிறிஸ்",
    someoneEmail: "someone@gmail.com",
    forSuppliers: "சப்ளையர்களுக்கு",
    forSuppliersPara:
      "நீங்கள் கடற்பாசி உற்பத்தியாளர், சப்ளையர் அல்லது உற்பத்தியாளர் உங்கள் வரம்பை விரிவுபடுத்தி, உலகளாவிய வாங்குபவர்களின் நெட்வொர்க்குடன் இணைக்க விரும்புகிறீர்களா? மேலும் பார்க்க வேண்டாம் - எங்கள் விற்பனையாளர்கள் பக்கம் செழித்து வரும் கடற்பாசி துறையில் வாய்ப்புகளின் உலகத்திற்கான உங்கள் நுழைவாயிலாகும்.",
    supplierInformationForm: "சப்ளையர் தகவல் படிவம்",
    organisationName: "அமைப்பின் பெயர்",
    organisationWebsite: "அமைப்பின் இணையதளம்",
    yourinterest: "நீங்கள் எதை விற்க ஆர்வமாக உள்ளீர்கள்",
    dummyWebsite: "www.algaestore.in",
    tellWhatSelling:
      "நீங்கள் எதை விற்கிறீர்கள் என்பதைப் பற்றி மேலும் சொல்லுங்கள்!",
    productTypes: "தயாரிப்பு வகைகள்",
    sargassum: "சர்காசும்",
    sargassumPara:
      "சர்காசம் ஒரு பழுப்பு நிற மேக்ரோஅல்கா கடற்பாசி ஆகும். இந்த இனங்கள் பல உலகின் சூடான மற்றும் வெப்பமண்டல பெருங்கடல்கள் முழுவதும் விநியோகிக்கப்படுகின்றன, அங்கு அவை பொதுவாக ஆழமற்ற நீர் மற்றும் பவளப்பாறைகளில் வாழ்கின்றன. சர்காசம் அதன் இலவச-மிதக்கும் வளர்ச்சி முறைக்காக பரவலாக அறியப்படுகிறது மற்றும் இந்த கடற்பாசி உரம், பயோபிளாஸ்டிக் மற்றும் கால்நடை தீவனத் தொழில்களால் பரவலாகப் பயன்படுத்தப்படுகிறது.",
    kappaphycusAlvarezii: "கப்பாபிகஸ் அல்வாரெஸி",
    kappaphycusAlvareziiPara:
      "Kappaphycus alvarezii என்பது கராஜீனன் உற்பத்தி செய்யும் கடற்பாசி ஆகும், இது பொதுவாக கேரஜீனன் தொழிற்சாலைகளுக்கு மூலப்பொருளாகப் பயன்படுத்தப்படுகிறது. கேரஜீனன் முக்கியமாக உணவு, பானம், அழகுசாதனப் பொருட்கள், மருந்து, பெயிண்ட், ஜவுளி மற்றும் பிற தொழில்களுக்கான சேர்க்கைகளாகப் பயன்படுத்தப்படுகிறது. கரிம உரங்களுக்கு நன்மை பயக்கும் வளர்ச்சி ஹார்மோனின் ஆதாரமாகவும் பருத்தி கடற்பாசிகளைப் பயன்படுத்தலாம்.",
    ulvaLactuca: "உல்வா லாக்டுகா",
    ulvaLactucaPara:
      "உல்வா, கடல் கீரை என்றும் அழைக்கப்படுகிறது, இது ஒரு உண்ணக்கூடிய பச்சை ஆல்கா ஆகும், இது பாறைகள், சரளை மற்றும் பவளப்பாறைகளில் ஒட்டிக்கொண்டு வாழும் ஒரு கடற்பாசி ஆகும், ஆனால் சில நேரங்களில் அது கடலில் மிதப்பதைக் காணலாம்.",
    geledium: "ஜெலிடியம்",
    gelediumPara:
      "பல நாடுகளில், கெலிடியம் என்பது உயர்தர அகார் பிரித்தெடுப்பதற்கு பரவலாகப் பயன்படுத்தப்படும் மூலப்பொருளாகும். ஜெலிடியத்தின் உள்ளடக்கம் கிளாசிலேரியாவை விட அதிகமாக உள்ளது. பாரம்பரியமாக ஜெலிடியம் ஒரு காய்கறியாகவும், ஜெல்லி ஜெல்லி தயாரிக்கவும் உட்கொள்ளப்படுகிறது. ஜெலிடியம் பெரும்பாலும் பச்சையாக உண்ணப்படுகிறது, ஆனால் பரிமாறும் முன் ஆவியில் வேகவைத்து அல்லது சமைத்து மூலிகைகளுடன் கலக்கலாம்.",
    gracillaria: "கிரேசிலாரியா",
    gracillariaPara:
      "கிரேசில்லாரியா பொதுவாக உண்ணக்கூடிய ஜெலட்டின் உற்பத்திக்கான முக்கிய மூலப்பொருளாகப் பயன்படுத்தப்படுகிறது. உணவுப் பயன்பாடுகளுக்கு, இது முக்கியமாக உணவு நார்ச்சத்து, திடப்படுத்தும் முகவர், பல்வேறு பானங்களின் கலவை, தடித்தல் மற்றும் உறுதிப்படுத்தும் முகவர் ஆகியவற்றின் மூலமாகப் பயன்படுத்தப்படுகிறது. உணவு அல்லாத பயன்பாடுகளுக்கு, Glacilaria ஒப்பனை தொழில்துறையில் பயன்படுத்தப்படுகிறது; ஷாம்பு, கிரீம், சன்ஸ்கிரீன், பற்பசை மற்றும் மருந்துத் தொழில்கள்.",
    getInTouch: "தொடர்பில் இருங்கள்",
    getInTouchPara:
      "உதவி அல்லது புதிய வெற்றிகரமான கூட்டாண்மைக்காகத் தேடுகிறீர்களா? உங்கள் கேள்வியின் சில விவரங்களுடன் எங்களுக்கு ஒரு செய்தியை அனுப்பவும். நாங்கள் உங்களுக்கு உதவ மகிழ்ச்சியாக இருப்போம். 1 வணிக நாளுக்குள் நாங்கள் பதிலளிக்கிறோம்.",
    contactForm: "தொடர்பு படிவம்",
    yourName: "உங்கள் பெயர்",
    yourContactEmail: "உங்கள் தொடர்பு மின்னஞ்சல்",
    yourMessage: "உங்கள் தகவல்",
    submit: "சமர்ப்பிக்கவும்",
    enterSearch: "உங்கள் தேடலை இங்கே உள்ளிடவும்",
    search: "தேடு",
    filters: "வடிப்பான்கள்",
    harvested: "அறுவடை செய்யப்பட்டது",
    processed: "செயலாக்கப்பட்டது",
    finishedGoods: "இறுதி பொருட்கள்",
    wetSeaweed: "ஈரமான கடற்பாசி",
    drySeaweed: "உலர் கடற்பாசி",
    seedMaterial: "விதை பொருள்",
    all: "அனைத்து",
    extractSap: "சாறு / சாறு",
    pulverizedSeaweed: "தூளாக்கப்பட்ட கடற்பாசி",
    powderedSeaweed: "தூள் கடலை",
    hydrocolloids: "ஹைட்ரோகலாய்டுகள்",
    cellulosicResidue: "செல்லுலோசிக் எச்சம்",
    agriculture: "வேளாண்மை",
    food: "உணவு",
    packaging: "பேக்கேஜிங்",
    fuel: "எரிபொருள்",
    textile: "ஜவுளி",
    cart: "வண்டி",
    removeItem: "பொருளை அகற்று",
    clearCart: "தெளிவான வண்டி",
    proceed: "தொடரவும்",
    checkout: "சரிபார்",
    selectedItems: "தேர்ந்தெடுக்கப்பட்ட பொருட்கள்",
    purchaseMemo: "பர்ச்சேஸ் மெமோ",
    number: "எண்",
    name: "பெயர்",
    price: "விலை",
    back: "மீண்டும்",
    placeOrder: "ஆர்டர் வைக்கவும்",
    orderSubmittedSuccessfully:
      "உங்கள் ஆர்டர் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது, எங்கள் பிரதிநிதி விரைவில் உங்களைத் தொடர்புகொள்வார்.",
    productAddedSuccessfully: "தயாரிப்பு வெற்றிகரமாக சேர்க்கப்பட்டது.",
    somethingWentWrong:
      "ஏதோ தவறு நடந்துவிட்டது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
    buyingRequestSent:
      "உங்கள் வாங்குதல் கோரிக்கை எங்கள் நிர்வாகிக்கு அனுப்பப்பட்டது, விரைவில் உங்களைத் தொடர்புகொள்வோம்.",
    messageSent:
      "உங்கள் செய்தி நிர்வாகிக்கு அனுப்பப்பட்டது, விரைவில் உங்களைத் தொடர்புகொள்வோம்",
    passwordShouldMatch:
      "கடவுச்சொல் மற்றும் உறுதிப்படுத்தல் கடவுச்சொல் பொருந்த வேண்டும்.",
    passwordLength:
      "கடவுச்சொல் 8ஐ விட அதிகமாகவோ அல்லது சமமாகவோ இருக்க வேண்டும்",
    invalidEmailAddress: "சரியான மின்னஞ்சல் முகவரியை வழங்கவும்.",
    sellingRequestSent:
      "உங்கள் விற்பனை கோரிக்கை எங்கள் நிர்வாகிக்கு அனுப்பப்பட்டது, விரைவில் உங்களைத் தொடர்புகொள்வோம்.",
    noItemInCart: "வண்டியில் பொருள் இல்லை",
    editProfile: "சுயவிவரத்தைத் திருத்து",
    logout: "வெளியேறு",
    publishedProduct: "வெளியிடப்பட்ட தயாரிப்பு",
    welcomeAlgaeStore: "பாசி கடைக்கு வரவேற்கிறோம்",
    pleaseLogin: "உங்கள் கணக்கில் உள்நுழையவும்",
    username: "பயனர் பெயர்",
    password: "கடவுச்சொல்",
    logIn: "உள்நுழைய",
    moreThanStore: "நாங்கள் ஒரு கடையை விட அதிகம்",
    loginPara:
      "அனைத்து தயாரிப்புகளையும் ஆராய, உங்கள் தயாரிப்பை வாங்க அல்லது விற்க உள்நுழைக.",
    orders: "ஆர்டர்கள்",
    wishlist: "விருப்பப்பட்டியல்",
    reviews: "விமர்சனங்கள்",
    suppliers: "சப்ளையர்கள்",
    exploreAllProducts: "அனைத்து தயாரிப்புகளையும் ஆராயுங்கள்",
    introducing: "அறிமுகப்படுத்துகிறது",
    premiumHub: "கடற்பாசி வர்த்தகத்திற்கான உங்கள் பிரீமியர் B2B ஹப்",
    total: "மொத்தம்",
    changeEmail: "மின்னஞ்சலை மாற்று (விரும்பினால்)",
    dontHaveAccount: "கணக்கு இல்லையா?",
    register: "பதிவு",
    createYour: "உங்கள் உருவாக்கவும்",
    emailOrPhone: "மின்னஞ்சல் அல்லது தொலைபேசி எண்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    alreadyAccount: "ஏற்கனவே ஒரு கணக்கு உள்ளதா?",
    account: "கணக்கு",
    createAccount: "உங்கள் கணக்கை துவங்குங்கள்",
    buyer: "வாங்குபவர்",
    seller: "விற்பனையாளர்",
    orderHistory: "ஆர்டர் வரலாறு",
    goToStore: "எங்கள் கடையைப் பார்க்கவும்",
    algaeStoreForFarmers: "விவசாயிகளுக்கான பாசி கடை",
    connectWithUs: "Cஎங்களை தொடர்பு கொள்ளுங்கள்",
    algaeStoreForBuyers: "வாங்குபவர்களுக்கான பாசி கடை",
    buyerDetails: "வாங்குபவர் விவரங்கள்",
    mobileNumber: "கைபேசி எண்",
    industry: "தொழில்",
    additionalInfo: "கூடுதல் தகவல்",
    takePainOut: "கொள்முதல் வலியை எடுத்துக் கொள்ளுங்கள்",
    algaeStoreForBuyerInfo:
      "ஆல்கா ஸ்டோர் என்பது உயிரியல் அடிப்படையிலான இரசாயனங்கள், பொருட்கள், பொருட்கள் மற்றும் முடிக்கப்பட்ட தயாரிப்புகளை கண்டுபிடிப்பதற்கும் வாங்குவதற்கும் ஒரே இடத்தில் உள்ளது",
    buyingStep1: "வாங்குதல் கோரிக்கையைச் சமர்ப்பிக்கவும்",
    buyingStep2:
      "ஆல்கே ஸ்டோர் கோரிக்கையை சப்ளையர் நெட்வொர்க்குடன் பகிர்ந்து கொள்கிறது",
    buyingStep3:
      "விவரக்குறிப்புகள், மேற்கோள்கள் மற்றும் தொடர்புடைய சப்ளையர்களுக்கு நேரடி அறிமுகங்கள் ஆகியவற்றைப் பெறுங்கள்",
    noCost:
      "ஆல்கா ஸ்டோரின் சேவைகளுக்கு வாங்குபவர்களுக்கு கட்டணம் இல்லை. முடிக்கப்பட்ட விற்பனையில் சப்ளையர்கள் எங்களுக்கு ஒரு கட்டணத்தை செலுத்துகிறார்கள்.",
    gainNewCustomers: "தொந்தரவு இல்லாமல் புதிய வாடிக்கையாளர்களைப் பெறுங்கள்",
    algaeStoreProvides:
      "ஆல்கே ஸ்டோர் சப்ளையர்களுக்கு வாங்கும் கோரிக்கைகள் மற்றும் உயிர் அடிப்படையிலான தயாரிப்புகளைத் தேடும் வாடிக்கையாளர்களுக்கு அறிமுகம் ஆகியவற்றை வழங்குகிறது.",
    submitSupplierInfo: "சப்ளையர் தகவல் படிவத்தை சமர்ப்பிக்கவும்.",
    step1: "படி 1",
    step2: "படி 2",
    step3: "படி 3",
    scheduleAnOnboarding:
      "நிறுவனம் மற்றும் தயாரிப்புப் பட்டியலை முடிக்க, ஆல்கே ஸ்டோருடன் ஒரு ஆன்போர்டிங் அழைப்பைத் திட்டமிடுங்கள்.",
    reciveBuyingRequests:
      "சாத்தியமான வாடிக்கையாளர்களிடமிருந்து வாங்குதல் கோரிக்கைகளைப் பெறுங்கள்.",
    noUpfrontCost:
      "நிறுவனம் மற்றும் தயாரிப்பு பட்டியல்களுக்கு சப்ளையர்களுக்கு முன்கூட்டிய கட்டணம் எதுவும் இல்லை. ஆன்போர்டிங் செயல்முறையின் ஒரு பகுதியாக, முடிக்கப்பட்ட விற்பனைக்கான கட்டணத்தை நாங்கள் ஒப்புக்கொள்கிறோம்.",
  },
};

export { LANGUAGE, LANGUAGE_TYPE };
